// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezamzkycxqrstuznqaha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6YW16a3ljeHFyc3R1em5xYWhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzMTQ1MDQsImV4cCI6MjA4Mzg5MDUwNH0.fdXx5zzxS3NUw1RCHCyhl783qTws6lARgZs2GOaDn2k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});